### ISSUE TITLE
TileJSON

### ISSUE THREAD

**Issue by tmcw** [zzolo/tilemill-viewer#2]
Hey - TileMill does provide TileJSON endpoints, like http://localhost:20009/api/Project/Maze/ for a project called Maze. These also support JSONP when given a `callback` parameter.

**Comment by zzolo** [comment]
Oh, awesome.  I was looking through the code, but was really only looking at the Tile server part (https://github.com/mapbox/tilemill/blob/master/servers/Tile.bones).

Many thanks, will update it soon.
